--delete  from AspNetRoles;
--delete  from AspNetUserLogins;
--delete  from tblAppointmentStatus;
--delete  from tblAppointmentTypes;
--delete  from tblCandidateStatus;
--delete  from tblJobVacanciesStatus;
--delete  from tblMSPQuestions;
--delete  from tblMSPRequiredDocument;
--delete  from tblMSPSpendCategory;
--delete  from tblMSPTimeGroup;
--delete  from tblTimesheetStatus;
--delete  from tblFileTypes;
--delete  from tblMSPVacancieTypes;
TRUNCATE TABLE tblCandidateContacts;
TRUNCATE TABLE tblCandidateFiles;
TRUNCATE TABLE tblCandidateIndustries;
TRUNCATE TABLE tblCandidateSkills;
TRUNCATE TABLE tblCandidateSubmissionAppointmentSlots;
TRUNCATE TABLE tblCandidateSubmissionAppointmentUserComments;
TRUNCATE TABLE tblCandidateSubmissionAppointmentUsers;
TRUNCATE TABLE tblCandidateSubmissionComments;
TRUNCATE TABLE tblCandidateSubmissionDocumentResponses;
delete from tblCandidateSubmissionSpend;
DBCC CHECKIDENT (tblCandidateSubmissionSpend, RESEED, 0);
TRUNCATE TABLE tblCandidateSubmissionSpendFiles;
TRUNCATE TABLE tblCandidateSubmissionsQuestionsResponses;
TRUNCATE TABLE tblCandidateTimesheetCategoriesHours;
TRUNCATE TABLE tblCandidateTimesheetHours;
delete from tblCandidateTimesheets;
DBCC CHECKIDENT (tblCandidateTimesheets, RESEED, 0);
TRUNCATE TABLE tblCommentUsers;
delete from tblContacts;
DBCC CHECKIDENT (tblContacts, RESEED, 0);
TRUNCATE TABLE tblCustomerLocationBranches;
TRUNCATE TABLE tblCustomerUsers;
delete from tblFiles;
DBCC CHECKIDENT (tblFiles, RESEED, 0);
TRUNCATE TABLE tblMSPCustomers;
TRUNCATE TABLE tblMSPLocationBranches;
delete from tblMSPPayPeriods;
DBCC CHECKIDENT (tblMSPPayPeriods, RESEED, 0);
TRUNCATE TABLE tblMSPTimeCategories;
delete from tblMSPTimeGroupCategories;
DBCC CHECKIDENT (tblMSPTimeGroupCategories, RESEED, 0);
delete  from tblMSPUsers where UserID !='afcf8230-7878-4e1d-a550-532fd10769ae';
TRUNCATE TABLE tblSupplierCandidates;
TRUNCATE TABLE tblSupplierLocationBranches;
TRUNCATE TABLE tblSupplierUsers;
TRUNCATE TABLE tblUserLocationBranches;
delete  from tblUserProfile where UserID !='afcf8230-7878-4e1d-a550-532fd10769ae';
TRUNCATE TABLE tblVacancieSkills;
delete from tblVacanciesQuestions;
DBCC CHECKIDENT (tblVacanciesQuestions, RESEED, 0);
delete from tblVacanciesRequiredDocuments;
DBCC CHECKIDENT (tblVacanciesRequiredDocuments, RESEED, 0);
TRUNCATE TABLE tblVacancyComments;
TRUNCATE TABLE tblVacancyFiles;
TRUNCATE TABLE tblVacancyLocations;
TRUNCATE TABLE tblVacancySuppliers;
delete from tblBranches;
DBCC CHECKIDENT (tblBranches, RESEED, 0);
delete from tblCandidatePlacements;
DBCC CHECKIDENT (tblCandidatePlacements, RESEED, 0);
delete from tblCandidateSubmissionAppointments;
DBCC CHECKIDENT (tblCandidateSubmissionAppointments, RESEED, 0);
delete from tblComments;
DBCC CHECKIDENT (tblComments, RESEED, 0);
delete from tblIndustrySkills;
DBCC CHECKIDENT (tblIndustrySkills, RESEED, 0);
delete from tblLocations;
DBCC CHECKIDENT (tblLocations, RESEED, 0);
delete from tblSupplier;
DBCC CHECKIDENT (tblSupplier, RESEED, 0);
delete  from AspNetUsers where Id !='afcf8230-7878-4e1d-a550-532fd10769ae';
delete from tblCandidateSubmission;
DBCC CHECKIDENT (tblCandidateSubmission, RESEED, 0);
delete from tblCandidates;
DBCC CHECKIDENT (tblCandidates, RESEED, 0);
delete from tblIndustries;
DBCC CHECKIDENT (tblIndustries, RESEED, 0);
delete from tblVacancies;
DBCC CHECKIDENT (tblVacancies, RESEED, 0);
delete from tblCustomers;
DBCC CHECKIDENT (tblCustomers, RESEED, 0);
delete  from tblMSPDetails where ID !=1;
update tblUserProfile set StateID=1,CountryID=3;
update tblMSPDetails set StateID=1,CountryID=3;
delete  from tblCountryStates where ID !=1;
delete  from tblCountries where ID !=3;
delete  from AspNetRoleGroupRoles where RoleGroupId in(select Id from AspNetRoleGroups where Name !='Admin');
delete  from AspNetRoleGroups where Name !='Admin';
delete  from AspNetUserRoles where UserID !='afcf8230-7878-4e1d-a550-532fd10769ae';
