//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMSP.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCandidateTimesheetCategoriesHour
    {
        public long ID { get; set; }
        public long TimesheetID { get; set; }
        public long TimesheetCategoryID { get; set; }
        public System.DateTime TimeDate { get; set; }
        public decimal Hours { get; set; }
    
        public virtual tblCandidateTimesheet tblCandidateTimesheet { get; set; }
        public virtual tblMSPTimeGroupCategory tblMSPTimeGroupCategory { get; set; }
    }
}
