//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMSP.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCandidateSubmissionAppointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCandidateSubmissionAppointment()
        {
            this.tblCandidateSubmissionAppointmentSlots = new HashSet<tblCandidateSubmissionAppointmentSlot>();
            this.tblCandidateSubmissionAppointmentUsers = new HashSet<tblCandidateSubmissionAppointmentUser>();
        }
    
        public long ID { get; set; }
        public long AppintmentTypeID { get; set; }
        public long CandidateSubmissionID { get; set; }
        public long AppointmentStatusID { get; set; }
        public string Name { get; set; }
        public string Details { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public string CreatedUserID { get; set; }
        public Nullable<System.DateTime> UpdatedTimestamp { get; set; }
        public string UpdatedUserID { get; set; }
    
        public virtual tblAppointmentStatu tblAppointmentStatu { get; set; }
        public virtual tblAppointmentType tblAppointmentType { get; set; }
        public virtual tblCandidateSubmission tblCandidateSubmission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCandidateSubmissionAppointmentSlot> tblCandidateSubmissionAppointmentSlots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCandidateSubmissionAppointmentUser> tblCandidateSubmissionAppointmentUsers { get; set; }
    }
}
