//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMSP.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCandidateSubmission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCandidateSubmission()
        {
            this.tblCandidateSubmissionAppointments = new HashSet<tblCandidateSubmissionAppointment>();
            this.tblCandidateSubmissionComments = new HashSet<tblCandidateSubmissionComment>();
        }
    
        public long ID { get; set; }
        public long VacancyID { get; set; }
        public long CandidateID { get; set; }
        public long StatusID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public string CreatedUserID { get; set; }
        public Nullable<System.DateTime> UpdatedTimestamp { get; set; }
        public string UpdatedUserID { get; set; }
        public decimal BillRate { get; set; }
    
        public virtual tblCandidate tblCandidate { get; set; }
        public virtual tblCandidateStatu tblCandidateStatu { get; set; }
        public virtual tblVacancy tblVacancy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCandidateSubmissionAppointment> tblCandidateSubmissionAppointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCandidateSubmissionComment> tblCandidateSubmissionComments { get; set; }
    }
}
