//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMSP.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCandidateSubmissionDocumentRespons
    {
        public long ID { get; set; }
        public long CandidateSubmissionID { get; set; }
        public long VacancyRequiredDocumentID { get; set; }
        public long CandidateFileID { get; set; }
        public Nullable<long> CommentID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public string CreatedUserID { get; set; }
        public Nullable<System.DateTime> UpdatedTimestamp { get; set; }
        public string UpdatedUserID { get; set; }
    
        public virtual tblCandidateFile tblCandidateFile { get; set; }
        public virtual tblCandidateSubmission tblCandidateSubmission { get; set; }
        public virtual tblComment tblComment { get; set; }
        public virtual tblVacanciesRequiredDocument tblVacanciesRequiredDocument { get; set; }
    }
}
