//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMSP.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMSPTimeGroupCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMSPTimeGroupCategory()
        {
            this.tblCandidateTimesheetCategoriesHours = new HashSet<tblCandidateTimesheetCategoriesHour>();
        }
    
        public long ID { get; set; }
        public long GroupID { get; set; }
        public long CategoryID { get; set; }
        public decimal WeeklyMarkup { get; set; }
        public int DailyMaxHours { get; set; }
        public int WeeklyMaxHours { get; set; }
        public int MonthlyMaxHours { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public string CreatedUserID { get; set; }
        public Nullable<System.DateTime> UpdatedTimestamp { get; set; }
        public string UpdatedUserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCandidateTimesheetCategoriesHour> tblCandidateTimesheetCategoriesHours { get; set; }
    }
}
